server:
  port: 5050

spring:
  application:
    name: luxin-auth
  redis:
    password: lzt4922
    port: 6379
    host: 192.168.222.1

xxl:
  job:
    admin:
      addresses: http://localhost:7070/admin
    executor:
      appname: xxl-luxin
      ip:
      port: 9998
      logpath: ./logs/xxl/job
      logretentiondays: -1
    accessToken:

